function fun()
{
    $("#circle1").fadeTo(500, 0.9);
}
function buttontogg1()
{
    $("#btt1").hide();
    parallax["features"].right();
    $("#btt2").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg2()
{
    $("#btt2").hide();
    parallax["bug2"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg3()
{
    $("#btt3").hide();
    parallax["bug3"].right();
    $("#btt1").show();
    $("#btt2").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg4()
{
    $("#btt4").hide();
    parallax["bug4"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt2").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg5()
{
    $("#btt5").hide();
    parallax["bug5"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt2").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg6()
{
    $("#btt6").hide();
    parallax["bug6"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt2").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg7()
{
    $("#btt7").hide();
    parallax["bug7"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt2").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg8()
{
    $("#btt8").hide();
    parallax["bug8"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt2").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg9()
{
    $("#btt9").hide();
    parallax["bug9"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt2").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg10()
{
    $("#btt10").hide();
    parallax["bug10"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt2").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg11()
{
    $("#btt11").hide();
    parallax["bug11"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt2").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg12()
{
    $("#btt12").hide();
    parallax["bug12"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt2").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg13()
{
    $("#btt13").hide();
    parallax["bug13"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt2").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg14()
{
    $("#btt14").hide();
    parallax["bug14"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt2").show();
    $("#btt15").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg15()
{
    $("#btt15").hide();
    parallax["bug15"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg16()
{
    $("#btt16").hide();
    parallax["bug16"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg17()
{
    $("#btt17").hide();
    parallax["bug17"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt15").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg18()
{
    $("#btt18").hide();
    parallax["bug18"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt15").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg19()
{
    $("#btt19").hide();
    parallax["bug19"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt15").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg20()
{
    $("#btt20").hide();
    parallax["bug20"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt15").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg21()
{
    $("#btt21").hide();
    parallax["bug21"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt15").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg22()
{
    $("#btt22").hide();
    parallax["bug22"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt15").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg23()
{
    $("#btt23").hide();
    parallax["bug23"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt15").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg24()
{
    $("#btt24").hide();
    parallax["bug24"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt15").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg25()
{
    $("#btt25").hide();
    parallax["bug25"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt15").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg26()
{
    $("#btt26").hide();
    parallax["bug26"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt15").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg27()
{
    $("#btt27").hide();
    parallax["bug27"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt15").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg28()
{
    $("#btt28").hide();
    parallax["bug28"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt15").show();
    $("#btt29").show();
    $("#btt30").show();
   
}
function buttontogg29()
{
    $("#btt29").hide();
    parallax["bug29"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt2").show();
    $("#btt16").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt15").show();
    $("#btt30").show();
   
}
function buttontogg30()
{
    $("#btt30").hide();
    parallax["bug30"].right();
    $("#btt1").show();
    $("#btt3").show();
    $("#btt4").show();
    $("#btt5").show();
    $("#btt6").show();
    $("#btt7").show();
    $("#btt8").show();
    $("#btt9").show();
    $("#btt10").show();
    $("#btt11").show();
    $("#btt12").show();
    $("#btt13").show();
    $("#btt14").show();
    $("#btt15").show();
    $("#btt2").show();
    $("#btt17").show();
    $("#btt18").show();
    $("#btt19").show();
    $("#btt20").show();
    $("#btt21").show();
    $("#btt22").show();
    $("#btt23").show();
    $("#btt24").show();
    $("#btt25").show();
    $("#btt26").show();
    $("#btt27").show();
    $("#btt28").show();
    $("#btt29").show();
    $("#btt15").show();
   
}